require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Tutorial' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'TutorialTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  #use_flipper!({ 'Flipper-Folly' => '2.5' }) # update this part
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   #react_native_post_install(installer)
	#   flipper_post_install(installer)
	#   installer.pods_project.build_configurations.each do |config|     
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"   
  #   end
  #   installer.pods_project.targets.each do |t|
  #     t.build_configurations.each do |bc|
  #           if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
  #               bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
  #           end
  #       end
  #   end
  # end
  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end 
  end
end